### ISSUE TITLE
NullPointerException during plugin initialization in gitbucket 4.35.3

### ISSUE THREAD

**Issue by keywordsalad** [alexandremenif/gitbucket-mirror-plugin#18]
The plugin does not initialize in gitbucket 4.35.3. I'll take a look and see what might be causing this, but a second head in the problem would be great too :)

```
23:55:57.120 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-mirror-plugin-1.3.0.jar
java.lang.NullPointerException: null
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:43)
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:15)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:223)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:208)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:91)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:54)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:309)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:284)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:92)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:60)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:60)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:561)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:787)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:368)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:277)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at JettyLauncher.main(JettyLauncher.java:148)
```

**Comment by omosun** [comment]
In the Official Docker image of gitbucket(4.37.2) and mysql this plugin(v1.4.0) does not initialize.
I get the same messages.

> gitbucket  | 23:26:55.788 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-mirror-plugin-1.4.0.jar
> gitbucket  | java.lang.NullPointerException: null
> gitbucket  |    at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:43)
omit

But It can work on the apache tomcat 9 with postgres.

thank you.

**Comment by omosun** [comment]
I understand the cause.
"renameColumn" Requires "columnDataType" for mysql.
https://docs.liquibase.com/change-types/rename-column.html

After modifying the "gitbucket-mirror_1.1.1.xml" file, you can now Initialize it for mysql.

**Comment by SIkebe** [comment]
@omosun Nice catch! Could you raise a PR ?

**Comment by omosun** [comment]
@Slkebe Certainly I could.
