### ISSUE TITLE
4.38.4 not supported?

### ISSUE THREAD

**Issue by Originalimoc** [alexandremenif/gitbucket-mirror-plugin#22]
should be a small change?

**Comment by Originalimoc** [comment]
well..
Log:
```
ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: gitbucket-mirror-plugin-1.4.0.jar
java.lang.NullPointerException: Cannot invoke "liquibase.datatype.LiquibaseDataType.toDatabaseDataType(liquibase.database.Database)" because the return value of "liquibase.datatype.DataTypeFactory.fromDescription(String, liquibase.database.Database)" is null
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:43)
	at liquibase.sqlgenerator.core.RenameColumnGenerator.generateSql(RenameColumnGenerator.java:15)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:220)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:206)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:94)
	at io.github.gitbucket.solidbase.migration.LiquibaseMigration.migrate(LiquibaseMigration.java:57)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:45)
	at io.github.gitbucket.solidbase.Solidbase.migrate(Solidbase.java:29)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3(PluginRegistry.scala:310)
	at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$3$adapted(PluginRegistry.scala:285)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistry.scala:285)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:91)
	at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:59)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
	at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
	at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
	at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:59)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4764)
```

**Comment by SIkebe** [comment]
Seem to be a same one as #18. 
Could you wait until [v1.4.1](https://github.com/alexandremenif/gitbucket-mirror-plugin/milestone/6) is released?
(I will in about a week)

**Comment by Originalimoc** [comment]
Built one, it does work. Testing the functions.

**Comment by Originalimoc** [comment]
Releases won't get mirrored? Tags would though.

**Comment by soga-denken** [comment]
Is there any update on this issue?
I have the same issue.

I love this plugin, so It would be greatly appreciate that v1.4.1 is released.

Thanks.

**Comment by SIkebe** [comment]
@soga-denken Sorry for the delay. I'll release v1.4.1 by the end of this week.

**Comment by soga-denken** [comment]
@SIkebe Thank you for your kindness. I am looking forward to seeing new update!

**Comment by SIkebe** [comment]
I published [a new release](https://github.com/alexandremenif/gitbucket-mirror-plugin/releases/tag/v1.4.1). Could you try that version?

**Comment by soga-denken** [comment]
I have tried the new version and it worked fantastically 💯
GITBUCKET_VERSION: 4.39.0
mysql  Ver 8.0.33-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

**Comment by SIkebe** [comment]
Thank you for your confirmation!
